name: kafka-connect-jdbc
lang: java
lang_version: 8
git:
  enable: true
codeowners:
  enable: true
semaphore:
  enable: true
  pipeline_type: cp
  cve_scan: true
  extra_deploy_args: "-Dcloud -Pjenkins"
  extra_build_args: "-Dcloud -Pjenkins"
  run_pint_merge: true
  generate_connect_changelogs: true
code_artifact:
  enable: true
  package_paths:
    - maven-snapshots/maven/io.confluent/kafka-connect-jdbc
